---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: java
    tag: "8"

inputs:
- name: demo-out-repo

outputs:
- name: out-repo

run:
  path: /bin/bash
  args: 
    - demo-out-repo/ci/tasks/build-test
