---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: pcfservices/docker-concourse-cf-tools
    tag: "latest"

inputs:
- name: articulate-ci-demo

run:
  path: articulate-ci-demo/ci/tasks/run-unit-tests
