---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: java
    tag: "8"

inputs:
- name: articulate-ci-demo

outputs:
- name: out

run:
  path: articulate-ci-demo/ci/tasks/run-unit-tests
