---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: java
    tag: "8"

inputs:
- name: articulate-ci-demo

outputs:
- name: out-repo

run:
  path: /bin/bash
  args: 
    - articulate-ci-demo/ci/tasks/run-unit-tests
